# Default value for helmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
pdb:
  minAvailable: 0

terminationGracePeriodSeconds: 60

namespace: cam
serviceName: hello-world-helm
selectorLabels: hello-world-helm

image:
  repository: asajjan246/hello-world-app
  tag: 0.6

service:
  port: 80
  targetport: 8080

autoscaling:
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70