apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.selectorLabels }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.selectorLabels }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabels }}
    spec:
      containers:
      - name: {{ .Values.serviceName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetport }}
